#@baseUrl = http://3.34.97.118
@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzcwNzEzMDU1LCJleHAiOjE3NzA3MTY2NTV9.ViTVxr3EqPXi2aA4fByOJSIqaV1kyyMhMhYyZAHr86I
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzcwNzEzMDU1LCJleHAiOjE3NzA3OTk0NTV9.LRnpXtcmiU5Rsdi1JbfURsNnUN6JZDb9Xl9rD8HJbJw

###
POST {{baseUrl}}/auth/register
Cookie: access-token={{accessToken}}
Content-Type: application/json

{
  "email": "user9@example.com",
  "nickname": "user9",
  "password": "password8"
}


###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "password1"
}

###
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{accessToken}}



// 토큰 발행, 확인
###
POST {{baseUrl}}/auth/tokens/refresh
Cookie: refresh-token={{refreshToken}}

###
GET {{baseUrl}}/auth/tokens/view
Authorization: Bearer {{accessToken}}

