// 게시글 목록 조회
###
GET http://localhost:4000/articles?sort=&search=

// 게시글 생성
###
POST http://localhost:4000/articles
Content-Type: application/json

{
    "title": "d",
    "content": "d"
}

// 게시글 상세 조회
###
GET http://localhost:4000/articles/97feeee8-b482-47b5-bf96-272751fdaa66

// 게시글 수정
###
PATCH http://localhost:4000/articles/ada26136-cf9d-468b-88e0-4d1d315145fe
Content-Type: application/json

{
    "title": "게시글 수정",
    "content": "사람 입니다."
}

// 게시글 삭제
###
DELETE http://localhost:4000/articles/ada26136-cf9d-468b-88e0-4d1d315145fe

