@host=http://localhost:3000
@accessToken={{login.response.body.accessToken}}

###
# @name login
POST {{host}}/auth/login
Content-Type: application/json

# {
#   "email": "3d73fs3d83fy.3d53g53hz@gmail.com",
#   "password": "password1234"
# }

{
  "email": "sadqueen400@naver.com",
  "password": "password1234"
}

# {
#   "email": "sadqueen02@naver.com",
#   "password": "password1234"
# }

###
POST {{host}}/auth/logout
Authorization: Bearer {{accessToken}}
Content-Type: application/json


###
GET {{host}}/notifications/unread
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
PATCH {{host}}/notifications/9babfd3f-47ba-4f94-8482-e52693f06a8a/read
Authorization: Bearer {{accessToken}}
Content-Type: application/json


###
GET {{host}}/notifications/
Authorization: Bearer {{accessToken}}
Content-Type: application/json