export const userSample = [
  {
    email: 'test1@test.com',
    nickname: 'tester1',
    password: 'qwer1234',
    image: 'test1.jpg',
  },
  {
    email: 'test2@test.com',
    nickname: 'tester2',
    password: 'qwer1234',
    image: 'test2.jpg',
  },
  {
    email: 'test3@test.com',
    nickname: 'tester3',
    password: 'qwer1234',
    image: 'test3.jpg',
  },
  {
    email: 'test4@test.com',
    nickname: 'tester4',
    password: 'qwer1234',
    image: 'test4.jpg',
  },
  {
    email: 'test5@test.com',
    nickname: 'tester5',
    password: 'qwer1234',
    image: 'test5.jpg',
  },
];

export const productSample = [
  {
    name: '로봇',
    description: '어린이용 변신 로봇',
    price: 5000,
    tags: ['어린이', '장난감'],
    images: ['img1.jpg', 'img1.png'],
    userId: 1,
  },
  {
    name: '인형',
    description: '공주님 인형',
    price: 50000,
    tags: ['어린이', '장난감'],
    images: ['img2.jpg', 'img2.png'],
    userId: 1,
  },
  {
    name: '축구공',
    description: '2026 리뉴얼 축구공',
    price: 10000,
    tags: ['어린이', '장난감', '야외'],
    images: ['img3.jpg', 'img3.png'],
    userId: 1,
  },
  {
    name: '의사놀이',
    description: '의사놀이 전용 장난감 셋트',
    price: 25000,
    tags: ['어린이', '장난감', '세트'],
    images: ['img4.jpg', 'img4.png'],
    userId: 1,
  },
  {
    name: '변신로봇 타이탄',
    description: '버튼으로 변신하는 대형 로봇',
    price: 18000,
    tags: ['어린이', '장난감'],
    images: ['robot1.jpg'],
    userId: 1,
  },
  {
    name: '레인보우 블록',
    description: '색감 학습용 블록 장난감',
    price: 12000,
    tags: ['어린이', '교육'],
    images: ['block1.jpg'],
    userId: 1,
  },
  {
    name: '미니 경찰차',
    description: '소리 나는 미니카',
    price: 7000,
    tags: ['장난감', '탈것'],
    images: ['car1.jpg'],
    userId: 1,
  },
  {
    name: '공룡 피규어 세트',
    description: '티라노 포함 공룡 5종 세트',
    price: 22000,
    tags: ['장난감', '세트'],
    images: ['dino1.jpg'],
    userId: 1,
  },
  {
    name: '주방놀이 키트',
    description: '냄비와 식기 포함 역할놀이',
    price: 25000,
    tags: ['어린이', '역할놀이'],
    images: ['kitchen1.jpg'],
    userId: 1,
  },

  {
    name: '우주 탐사선',
    description: 'LED가 들어오는 우주선 장난감',
    price: 30000,
    tags: ['장난감', '과학'],
    images: ['space1.jpg'],
    userId: 1,
  },
  {
    name: '스케치 보드',
    description: '지우개 포함 그림판',
    price: 9000,
    tags: ['미술', '교육'],
    images: ['draw1.jpg'],
    userId: 1,
  },
  {
    name: '소프트 곰인형',
    description: '촉감 좋은 봉제 인형',
    price: 15000,
    tags: ['인형'],
    images: ['doll1.jpg'],
    userId: 1,
  },
  {
    name: '알파벳 퍼즐',
    description: '영어 학습 퍼즐',
    price: 13000,
    tags: ['교육', '퍼즐'],
    images: ['puzzle1.jpg'],
    userId: 1,
  },
  {
    name: '미니 농구대',
    description: '실내 설치용 농구대',
    price: 27000,
    tags: ['야외', '스포츠'],
    images: ['basket1.jpg'],
    userId: 1,
  },

  {
    name: 'RC 레이싱카',
    description: '리모컨 조종 자동차',
    price: 35000,
    tags: ['장난감', '전자'],
    images: ['rc1.jpg'],
    userId: 2,
  },
  {
    name: '캠핑 놀이 세트',
    description: '텐트와 모닥불 포함',
    price: 28000,
    tags: ['야외', '역할놀이'],
    images: ['camp1.jpg'],
    userId: 2,
  },
  {
    name: '마법 지팡이',
    description: '불빛과 소리 효과',
    price: 8000,
    tags: ['장난감', '판타지'],
    images: ['wand1.jpg'],
    userId: 2,
  },
  {
    name: '의사 놀이 가방',
    description: '청진기 포함 의료 놀이',
    price: 24000,
    tags: ['역할놀이'],
    images: ['doctor1.jpg'],
    userId: 2,
  },
  {
    name: '목공 놀이 툴킷',
    description: '안전한 공구 놀이',
    price: 26000,
    tags: ['교육', '세트'],
    images: ['tool1.jpg'],
    userId: 2,
  },

  {
    name: '미니 피아노',
    description: '소리 나는 건반 장난감',
    price: 19000,
    tags: ['음악'],
    images: ['piano1.jpg'],
    userId: 2,
  },
  {
    name: '동물 스티커북',
    description: '붙였다 떼는 스티커북',
    price: 6000,
    tags: ['교육', '책'],
    images: ['sticker1.jpg'],
    userId: 2,
  },
  {
    name: '비행기 글라이더',
    description: '손으로 날리는 글라이더',
    price: 5000,
    tags: ['야외', '장난감'],
    images: ['plane1.jpg'],
    userId: 2,
  },
  {
    name: '퍼즐 매트',
    description: '바닥용 쿠션 퍼즐',
    price: 32000,
    tags: ['유아', '매트'],
    images: ['mat1.jpg'],
    userId: 2,
  },
  {
    name: '드럼 놀이 세트',
    description: '리듬감 키우는 드럼',
    price: 21000,
    tags: ['음악', '장난감'],
    images: ['drum1.jpg'],
    userId: 2,
  },
];
