# 자동화 작업 이름
name : panda-market-cicd

# 작업 시점
on: 
  push :
    branches : # 1차 : "김지선" 브랜치 / 2차(최종) : "main" 브랜치 설정 
      - 김지선-sprint11 # action test용
      - 김지선
      - main
  pull_request :
    branches :
      - 김지선-sprint11 # action test용
      - 김지선
      - main

# 작업 내용
jobs:

  test:
    # run 환경
    runs-on: ubuntu-latest

    # DB 환경
    services: 
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test_pw_kjsnd6
          POSTGRES_DB: panda_action_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # 공통 환경변수
    env:
      # 테스트용 DB : 정보는 git secrets 저장
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NODE_ENV: test

      # 테스트용 임시 키 설정
      JWT_ACCESS_TOKEN_SECRET: "test_secret_key_12345" 
      JWT_REFRESH_TOKEN_SECRET: "test_secret_key_12345" 

      # 최종 작업에서는 git secret 사용, 현재는 규격만 맞춤
      AWS_REGION: "ap-northeast-2"        
      AWS_ACCESS_KEY_ID: "dummy_key"
      AWS_SECRET_ACCESS_KEY: "dummy_secret"
      AWS_BUCKET_NAME: "test-bucket"

    # test 작업 순서
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Type Check
        run: npm run typecheck

      - name: Run Tests
        run: 
          npx prisma migrate deploy
          npm run test