# 자동화 작업 이름
name : Deploy to EC2 panda-market

# 작업 시점
on: 
  push : 
    branches : 
      - 김지선 # 1차 : 상위 브랜치
      - main  # 2차 : 최종 브랜치
  # pull_request : 
  #   branches :
  #     - main

# 작업 내용
jobs:

  deploy:
    # run 환경
    if: github.repository == 'KimDay366/6-sprint-mission' # 현재 개인 레포지토리에만 secret 설정이 되어있어 해당 조건을 추가하였습니다
    runs-on: ubuntu-latest

    # 환경변수
    env:
      # DB 정보
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NODE_ENV: production

      # JWT 설정
      JWT_ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
      JWT_REFRESH_TOKEN_SECRET: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }} 

      # AWS 설정
      AWS_REGION: ${{ secrets.AWS_REGION }}      
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      
      # EC2 설정
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }} 
      

    # deploy 작업 순서
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/6-sprint-mission
            git pull origin ${{ github.ref_name }} # 최신 브랜치 자동 인식
            npm install 
            npm run build
            npm run prisma:deploy 
            pm2 reload panda-market || pm2 start dist/src/server.js --name "panda-market"
            echo "Deployment successful!"