name: Test
on:
  pull_request:
    branches: [main] # PR 발생 시 테스트

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '24.13.0'
      - run: npm ci
      - run: npx prisma migrate deploy
      - name: Type Check
        run: npm run typecheck
      - name: Run Tests
        run: npm run test
